In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dfx = pd.read_csv("psm_test.csv")
dfy = pd.read_csv("psm_test_label.csv")

In [20]:
dfx

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24
0,0.775374,0.909185,0.606704,0.660626,0.449968,0.426717,0.471591,0.434668,0.479511,0.478078,...,0.400617,0.480444,0.588670,0.404036,0.638957,0.020236,0.042705,0.173375,0.008715,0.105991
1,0.775423,0.909142,0.607796,0.660655,0.487813,0.442545,0.505682,0.448640,0.499451,0.494367,...,0.396902,0.500213,0.587041,0.421605,0.637865,0.018550,0.042705,0.191826,0.010893,0.110599
2,0.775458,0.909004,0.607988,0.660623,0.469532,0.433682,0.477273,0.450906,0.487223,0.484878,...,0.389270,0.487982,0.582404,0.407393,0.636091,0.018550,0.039146,0.188361,0.010893,0.115207
3,0.775513,0.909200,0.607218,0.660640,0.459910,0.435581,0.482955,0.454683,0.490431,0.488316,...,0.403780,0.491253,0.584660,0.407141,0.638138,0.020236,0.042705,0.186975,0.013072,0.110599
4,0.775587,0.909318,0.606654,0.660643,0.462155,0.436214,0.477273,0.449396,0.494671,0.487094,...,0.403636,0.495947,0.581527,0.402761,0.632678,0.021922,0.042705,0.156325,0.008715,0.110599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87836,0.864548,0.660041,0.590923,0.413322,0.364657,0.380184,0.494318,0.450529,0.382934,0.449698,...,0.394973,0.386574,0.755608,0.355207,0.835244,0.000000,0.028470,0.164872,0.021786,0.069124
87837,0.864483,0.536428,0.590742,0.413331,0.363695,0.378601,0.500000,0.451662,0.377564,0.315392,...,0.386467,0.381169,0.562101,0.349141,0.490718,0.000000,0.010676,0.157812,0.015251,0.069124
87838,0.864644,0.636236,0.590451,0.413619,0.348942,0.377018,0.488636,0.438822,0.373536,0.374673,...,0.413731,0.377329,0.640556,0.342261,0.700519,0.000000,0.028470,0.163298,0.015251,0.129032
87839,0.864553,0.643499,0.590222,0.413689,0.355997,0.379550,0.522727,0.448640,0.374963,0.435404,...,0.416956,0.378751,0.759744,0.343052,0.828556,0.000000,0.032028,0.150160,0.017429,0.059908
87840,0.864695,0.645337,0.590731,0.413732,0.357280,0.371637,0.482955,0.440710,0.377801,0.316390,...,0.405995,0.381454,0.546685,0.352665,0.617527,0.000000,0.003559,0.169520,0.013072,0.050691

In [7]:
dfx.drop("timestamp_(min)",axis=1,inplace=True)

In [8]:
dfy.drop("timestamp_(min)",axis=1,inplace=True)

In [14]:
dfy.head()

   label
0      0
1      0
2      0
3      0
4      0

In [12]:
dfy['label'].value_counts().reset_index()

   label  count
0      0  63460
1      1  24381

In [15]:
zero_columns = dfx.columns[dfx.eq(0).all()]
zero_columns

Index([], dtype='object')

In [16]:
dfx.isna().any().any()

False

In [18]:
mean0 = []
mean1 = []
median0 = []
median1 = []
std0 = []
std1 = []
for x in dfx.columns:
    mean0.append(np.mean(dfx[str(x)][dfy["label"] == 0]))
    mean1.append(np.mean(dfx[str(x)][dfy["label"] == 1]))
    median0.append(np.median(dfx[str(x)][dfy["label"] == 0]))
    median1.append(np.median(dfx[str(x)][dfy["label"] == 1]))
    std0.append(np.std(dfx[str(x)][dfy["label"] == 0]))
    std1.append(np.std(dfx[str(x)][dfy["label"] == 1]))

In [22]:
def calculate_per_change(old_value, new_value):
    percentage_change = ((new_value - old_value) / old_value) * 100
    return percentage_change

In [23]:
per_mean01 = []
per_mean10 = []
per_std01 = []
per_std10 = []
per_median01 = []
per_median10 = []
for i in range(len(std0)):
    per_mean01.append(calculate_per_change(mean0[i],mean1[i]))
    per_mean10.append(calculate_per_change(mean1[i],mean0[i]))
    per_std01.append(calculate_per_change(std0[i],std1[i]))
    per_std10.append(calculate_per_change(std1[i],std0[i]))
    per_median01.append(calculate_per_change(median0[i],median1[i]))
    per_median10.append(calculate_per_change(median1[i],median0[i]))

In [54]:
per_mean01_features = []
per_std01_features = []
per_median01_features = []
per_mean10_features = []
per_std10_features = []
per_median10_features = []
for i in range(len(std0)):
    if (per_mean01[i]>=5):
        x= per_mean01[i]
        per_mean01_features.append(dfx.columns[i])
    if (per_std01[i]>=50):
        x= per_std01[i]
        per_std01_features.append(dfx.columns[i])

    if (per_median01[i]>=20):
        x= per_median01[i]
        per_median01_features.append(dfx.columns[i])

    if (per_mean10[i]>=5):
        x= per_mean10[i]
        per_mean10_features.append(dfx.columns[i])
    if (per_std10[i]>=50):
        x= per_std10[i]
        per_std10_features.append(dfx.columns[i])
    if (per_median10[i]>=20):
        x= per_median10[i]
        per_median10_features.append(dfx.columns[i])

print(per_mean01_features)
print(per_std01_features)
print(per_median01_features)
print(per_mean10_features)
print(sorted(per_std10_features))
print(per_median10_features)

['feature_3', 'feature_18', 'feature_21', 'feature_22', 'feature_23']
['feature_2', 'feature_6', 'feature_10', 'feature_12', 'feature_13', 'feature_14', 'feature_18', 'feature_19', 'feature_20', 'feature_23']
['feature_21']
['feature_20']
[]
[]

In [55]:
from scipy.stats import pointbiserialr

correlation_coefficients = {}

for column in dfx.columns:
    # Calculate the point-biserial correlation between the input variable and the anomaly indicator
    correlation, p_value = pointbiserialr(dfx[column], dfy['label'])
    
    correlation_coefficients[column] = correlation

sorted_correlation_coefficients = sorted(correlation_coefficients.items(), key=lambda x: abs(x[1]), reverse=True)

for variable, coefficient in sorted_correlation_coefficients:
    print(f"Variable: {variable}, Point-Biserial Correlation: {coefficient}")

Variable: feature_22, Point-Biserial Correlation: 0.2496801543046729
Variable: feature_18, Point-Biserial Correlation: 0.20068129310788607
Variable: feature_15, Point-Biserial Correlation: 0.18639167213114383
Variable: feature_6, Point-Biserial Correlation: 0.1575880100519993
Variable: feature_1, Point-Biserial Correlation: 0.15099920150992938
Variable: feature_10, Point-Biserial Correlation: 0.1448569569554995
Variable: feature_3, Point-Biserial Correlation: 0.14254062537280668
Variable: feature_21, Point-Biserial Correlation: 0.13247745606695358
Variable: feature_13, Point-Biserial Correlation: 0.1280809070685113
Variable: feature_23, Point-Biserial Correlation: 0.1143674742575403
Variable: feature_19, Point-Biserial Correlation: 0.09298762283645531
Variable: feature_17, Point-Biserial Correlation: 0.08655027720217849
Variable: feature_24, Point-Biserial Correlation: 0.05791310836395365
Variable: feature_12, Point-Biserial Correlation: 0.047454351299214666
Variable: feature_2, Point-Biserial Correlation: 0.04562434668809801
Variable: feature_20, Point-Biserial Correlation: -0.04429663196478216
Variable: feature_14, Point-Biserial Correlation: 0.0401868305196485
Variable: feature_11, Point-Biserial Correlation: -0.03431179571578533
Variable: feature_5, Point-Biserial Correlation: -0.02472862053776159
Variable: feature_16, Point-Biserial Correlation: 0.023355228490287955
Variable: feature_9, Point-Biserial Correlation: -0.023258487974954785
Variable: feature_4, Point-Biserial Correlation: -0.023089937000745756
Variable: feature_8, Point-Biserial Correlation: 0.017378233917505474
Variable: feature_0, Point-Biserial Correlation: 0.014417053134113747
Variable: feature_7, Point-Biserial Correlation: -0.00127756013573251

### variables which are the root cause for the anomaly

on performing EDA on the data set:  
the variable which are the root cause of the anomaly are: **22, 18, 6, 15, 10, 21, 1**  
some other also are there: **3, 20, 13,19, 23**